export enum KINDS {
  ANY = 'any',
  ARRAY = 'array',
  CLASS = 'class',
  DESCRIPTION_LIST = 'descriptionList',
  EQUALS = 'equals',
  ERROR = 'error',
  FUNCTION = 'function',
  INCLUDE = 'include',
  INSTANCE_OF = 'instanceOf',
  INTEGER = 'integer',
  INTERFACE = 'interface',
  INTERNAL = 'internal',
  LITERAL = 'literal',
  MAYBE = 'maybe',
  NATIVE = 'native',
  NEVER = 'never',
  NIL = 'nil',
  OBJECT = 'object',
  OBJECT_INCLUDING = 'objectIncluding',
  OBJECT_WITHIN = 'objectMaybe',
  ONE_OF = 'oneOf',
  OPTIONAL = 'optional',
  PRIMITIVE = 'primitive',
  PROPERTIES_OF = 'propsOf',
  REFERENCE = 'reference',
  TUPLE = 'tuple',
  TYPE_OF = 'typeOf',
  UNION = 'union',
  UNKNOWN = 'unknown',
  UNRECOGNIZED = 'unrecognized',
  VOID = 'void',
  WITHIN = 'within',
  WHERE = 'where',
}

export const VALIDATION_TYPE_KEY = '__eveble_validation';
export const VALIDATION_PAYLOAD_KEY = '__eveble_payload';
